/* eslint-disable @next/next/no-img-element */
import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { AppLayout } from '../src/components/app';

export default function Blog() {
	return (
		<div>
			<Head>
				<title>Intrapair</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<AppLayout>
				<div className=' w-full relative'>
					<section className='container m-auto   px-[30px]'>
						<div className=' flex items-center  justify-center sm:pt-[120px] pb-[120px] py-9 '>
							<div className="h-[273px] xs:h-[387px] relative w-full bg-contain bg-center bg-no-repeat bg-[url('/common/flowery.png')] w-full">
								<div
									className='absolute top-[50%] left-[50%] w-full'
									style={{ transform: 'translate(-50%, -50%)' }}
								>
									<div className='flex flex-col gap-7 text-center items-center'>
										<div>
											<h1 className='text-dark-blue text-[30px] xs:text-[40px] sm:text-[60px] mlg:text-[64px] sm:leading-[70px] leading-[40px] mlg:leading-[94px] millimeter'>
												There’s Always Something To
											</h1>
											<h1 className='text-dark-blue text-[30px] xs:text-[40px] sm:text-[60px] mlg:text-[64px] sm:leading-[70px] leading-[40px] mlg:leading-[94px] millimeter'>
												Read About
											</h1>
										</div>
										<p className='text-black01 text-base'>
											Receive frequent tech updates curated by proficient
											writers at Intrapair. You don’t want to miss out on any of
											our exciting stories.
										</p>
										<button className='rounded-[41px] text-base w-[202px] bg-dark-blue text-white py-[15px] '>
											Prompt Me
										</button>
									</div>
								</div>
							</div>
						</div>
					</section>
					<section className=' pb-[189px]'>
						<div className='container px-[30px] m-auto'>
							<div className='flex flex-col gap-[70px]'>
								<div className='flex'>
									<div className='xl:flex-nowrap flex-wrap flex  gap-[36px] justify-between w-full'>
										<div
											className='flex flex-col gap-1 max-w-[300px]  items-center'
											style={{
												boxShadow:
													'0px 12px 16px -4px rgba(16, 24, 40, 0.08), 0px 4px 6px -2px rgba(16, 24, 40, 0.03)',
											}}
										>
											<div className='w-full'>
												<img src='/blog/blog1.png' alt='' />
											</div>
											<div className='flex flex-col gap-6 p-5 flex-1 w-full justify-between'>
												<p className='black01 text-base w-full sm:w-[80%]'>
													Lorem ipsum , consectetur adipiscing elit.
												</p>
												<div className='flex justify-between'>
													<p className='text-xs text-dark-blue'>31 Aug, 2022</p>
													<Image
														src={'/common/arrow-right.svg'}
														width={12}
														height={12}
														alt='>'
													/>
												</div>
											</div>
										</div>
										<div
											className='flex flex-col gap-1  max-w-[300px]  items-center'
											style={{
												boxShadow:
													'0px 12px 16px -4px rgba(16, 24, 40, 0.08), 0px 4px 6px -2px rgba(16, 24, 40, 0.03)',
											}}
										>
											<div className='w-full'>
												<img src='/blog/blog2.png' alt='' />
											</div>
											<div className='flex flex-col gap-6 p-5 flex-1 w-full justify-between'>
												<p className='black01 text-base w-full sm:w-[80%]'>
													Lorem ipsum , consectetur adipiscing elit.
												</p>
												<div className='flex justify-between'>
													<p className='text-xs text-dark-blue'>31 Aug, 2022</p>
													<Image
														src={'/common/arrow-right.svg'}
														width={12}
														height={12}
														alt='>'
													/>
												</div>
											</div>
										</div>
										<div
											className='flex flex-col gap-1   max-w-[300px] items-center'
											style={{
												boxShadow:
													'0px 12px 16px -4px rgba(16, 24, 40, 0.08), 0px 4px 6px -2px rgba(16, 24, 40, 0.03)',
											}}
										>
											<div className='w-full'>
												<img src='/blog/blog3.png' alt='' />
											</div>
											<div className='flex flex-col gap-6 p-5 flex-1 w-full justify-between'>
												<p className='black01 text-base w-full sm:w-[80%]'>
													Lorem ipsum , consectetur adipiscing elit.
												</p>
												<div className='flex justify-between'>
													<p className='text-xs text-dark-blue'>31 Aug, 2022</p>
													<Image
														src={'/common/arrow-right.svg'}
														width={12}
														height={12}
														alt='>'
													/>
												</div>
											</div>
										</div>
										<div
											className='flex flex-col gap-1  max-w-[300px] items-center'
											style={{
												boxShadow:
													'0px 12px 16px -4px rgba(16, 24, 40, 0.08), 0px 4px 6px -2px rgba(16, 24, 40, 0.03)',
											}}
										>
											<div className='w-full'>
												<img src='/blog/blog1.png' alt='' />
											</div>
											<div className='flex flex-col gap-6 p-5 flex-1 w-full justify-between'>
												<p className='black01 text-base w-full sm:w-[80%]'>
													Lorem ipsum , consectetur adipiscing elit.
												</p>
												<div className='flex justify-between'>
													<p className='text-xs text-dark-blue'>31 Aug, 2022</p>
													<Image
														src={'/common/arrow-right.svg'}
														width={12}
														height={12}
														alt='>'
													/>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div className='flex'>
									<div className='xl:flex-nowrap flex-wrap flex  gap-[36px] justify-between w-full'>
										<div
											className='flex flex-col gap-1 max-w-[300px]  items-center'
											style={{
												boxShadow:
													'0px 12px 16px -4px rgba(16, 24, 40, 0.08), 0px 4px 6px -2px rgba(16, 24, 40, 0.03)',
											}}
										>
											<div className='w-full'>
												<img src='/blog/blog1.png' alt='' />
											</div>
											<div className='flex flex-col gap-6 p-5 flex-1 w-full justify-between'>
												<p className='black01 text-base w-full sm:w-[80%]'>
													Lorem ipsum , consectetur adipiscing elit.
												</p>
												<div className='flex justify-between'>
													<p className='text-xs text-dark-blue'>31 Aug, 2022</p>
													<Image
														src={'/common/arrow-right.svg'}
														width={12}
														height={12}
														alt='>'
													/>
												</div>
											</div>
										</div>
										<div
											className='flex flex-col gap-1  max-w-[300px]  items-center'
											style={{
												boxShadow:
													'0px 12px 16px -4px rgba(16, 24, 40, 0.08), 0px 4px 6px -2px rgba(16, 24, 40, 0.03)',
											}}
										>
											<div className='w-full'>
												<img src='/blog/blog2.png' alt='' />
											</div>
											<div className='flex flex-col gap-6 p-5 flex-1 w-full justify-between'>
												<p className='black01 text-base w-full sm:w-[80%]'>
													Lorem ipsum , consectetur adipiscing elit.
												</p>
												<div className='flex justify-between'>
													<p className='text-xs text-dark-blue'>31 Aug, 2022</p>
													<Image
														src={'/common/arrow-right.svg'}
														width={12}
														height={12}
														alt='>'
													/>
												</div>
											</div>
										</div>
										<div
											className='flex flex-col gap-1   max-w-[300px] items-center'
											style={{
												boxShadow:
													'0px 12px 16px -4px rgba(16, 24, 40, 0.08), 0px 4px 6px -2px rgba(16, 24, 40, 0.03)',
											}}
										>
											<div className='w-full'>
												<img src='/blog/blog3.png' alt='' />
											</div>
											<div className='flex flex-col gap-6 p-5 flex-1 w-full justify-between'>
												<p className='black01 text-base w-full sm:w-[80%]'>
													Lorem ipsum , consectetur adipiscing elit.
												</p>
												<div className='flex justify-between'>
													<p className='text-xs text-dark-blue'>31 Aug, 2022</p>
													<Image
														src={'/common/arrow-right.svg'}
														width={12}
														height={12}
														alt='>'
													/>
												</div>
											</div>
										</div>
										<div
											className='flex flex-col gap-1  max-w-[300px] items-center'
											style={{
												boxShadow:
													'0px 12px 16px -4px rgba(16, 24, 40, 0.08), 0px 4px 6px -2px rgba(16, 24, 40, 0.03)',
											}}
										>
											<div className='w-full'>
												<img src='/blog/blog1.png' alt='' />
											</div>
											<div className='flex flex-col gap-6 p-5 flex-1 w-full justify-between'>
												<p className='black01 text-base w-full sm:w-[80%]'>
													Lorem ipsum , consectetur adipiscing elit.
												</p>
												<div className='flex justify-between'>
													<p className='text-xs text-dark-blue'>31 Aug, 2022</p>
													<Image
														src={'/common/arrow-right.svg'}
														width={12}
														height={12}
														alt='>'
													/>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</section>
				</div>
			</AppLayout>
		</div>
	);
}
