/* eslint-disable @next/next/no-img-element */
import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { AppLayout } from '../src/components/app';
import { SomethingGreat } from '../src/components/common';

export default function OpenSource() {
	return (
		<div>
			<Head>
				<title>Intrapair</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<AppLayout>
				<div className=' w-full relative'>
					<section className='container m-auto   px-[30px]'>
						<div className=' flex items-center  justify-center sm:py-[70px] py-9 '>
							<div className="h-[100px] xs:h-[387px] relative w-full bg-contain bg-center bg-no-repeat bg-[url('/common/flowery.png')] w-full text-center">
								<div
									className='absolute top-[50%] left-[50%]'
									style={{ transform: 'translate(-50%, -50%)' }}
								>
									<h1 className='text-dark-blue text-[30px] xs:text-[40px] sm:text-[60px] mlg:text-[64px] sm:leading-[70px] leading-[40px] mlg:leading-[94px] millimeter'>
										Fan Of Tech
									</h1>
									<h1 className='text-dark-blue text-[30px] xs:text-[40px] sm:text-[60px] mlg:text-[64px] sm:leading-[70px] leading-[40px] mlg:leading-[94px] millimeter'>
										Communities?{' '}
									</h1>
								</div>
							</div>
						</div>
					</section>

					<section className=' pb-[189px]'>
						<div className='container px-[30px] relative m-auto'>
							<div className='flex'>
								<div className='xl:flex block flex-wrap  gap-[36px] justify-between w-full items-center gap-[40px]'>
									<div className='flex flex-col gap-5 flex-1'>
										<p className='text-base text-black01'>
											We are enthusiastic about contributing to the tech
											ecosystem by creating free open-source solutions that
											enhance the work of developers, designers, content
											curators, and product managers. We hope to always share
											our knowledge with the world.
										</p>
										<button className='rounded-[41px]  text-sm w-[212px] bg-dark-blue text-white py-[15px]'>
											Collaborate With Us
										</button>
									</div>
									<div className='xl:my-0 my-9'>
										<Image
											className='m-auto'
											src={'/open-source/curly-arrow.png'}
											width={141}
											height={132}
											alt='==>'
										/>
									</div>

									<div className='flex-1'>
										<Image
											className='m-auto'
											src={'/open-source/open-source-illustration.png'}
											width={531}
											height={499}
											alt='>\open-source-illustration'
										/>
									</div>
								</div>
							</div>
							<div className='absolute bottom-[-152px] md:bottom-0 left-0'>
								<Image
									src={'/contact/blurry.png'}
									alt='blurry'
									width={171}
									height={171}
								/>
							</div>
						</div>
					</section>

					<SomethingGreat bgColor='#CCEDFF' />
				</div>
			</AppLayout>
		</div>
	);
}
